// TASK
export const GET_DATA_LIST_SUCCESS = '@user/GET_DATA_LIST_SUCCESS';
export const GET_DATA_LIST_FAILED = '@user/GET_DATA_LIST_FAILED';
export const SET_DATA_LIST_SUCCESS = '@user/SET_DATA_LIST_SUCCESS';
export const SET_DATA_LIST_FAILED = '@user/SET_DATA_LIST_FAILED';
export const DELETE_DATA_SUCCESS = '@user/DELETE_DATA_SUCCESS';
export const DELETE_DATA_FAILED = '@user/DELETE_DATA_FAILED';
export const SET_DATA_DONE_SUCCESS = '@user/SET_DATA_DONE_SUCCESS';
export const SET_DATA_DONE_FAILED = '@user/SET_DATA_DONE_FAILED';
